// qwik-app/src/components/CartItem.tsx
import { $, component$, PropFunction } from "@builder.io/qwik";
import { Product } from "~/types/types";

interface componentProps extends Omit<Product, "id"> {
  keyid: number;
  element: { quantity: number; startquantity: number };
  onRemove$: PropFunction<(id: number) => void>;
}
export default component$<componentProps>(
  ({ onRemove$, element, name, image, price, keyid, quantity, startquantity }) => {
    const decrease = $(() => {
      element.startquantity--;
    });

    const increase = $(() => {
      element.startquantity++;
    });

    return (
      <div
        data-key={keyid}
        class="cart-item flex items-center gap-6 rounded-lg bg-gray-100 p-4 shadow"
      >
        <img
          alt=""
          src={image}
          class="h-24 w-24 rounded-lg border object-cover"
          height="100"
          width="100"
        />
        <div class="flex-1">
          <h4 class="text-lg font-semibold text-gray-700">{name}</h4>
          <p class="text-gray-500">
            Price: <span class="font-bold text-gray-800">{`$ ${price}`}</span>
          </p>
          <div class="mt-2 flex items-center gap-2">
            <button
              onClick$={decrease}
              disabled={startquantity === 1}
              class="rounded bg-gray-300 px-2 py-1 hover:bg-gray-400"
            >
              -
            </button>
            <span class="rounded border bg-white px-3 py-1 text-gray-700">{startquantity}</span>
            <button
              onClick$={increase}
              disabled={quantity === startquantity}
              class="rounded bg-gray-300 px-2 py-1 hover:bg-gray-400"
            >
              +
            </button>
          </div>
        </div>
        <button class="rounded-md bg-red-900 p-1.5 text-white" onClick$={() => onRemove$(keyid)}>
          Remove
        </button>
      </div>
    );
  },
);

// src/components/cart/CartItem.vue
<script setup>
  import { useProductStore } from '@/stores/product';
  import { defineProps } from 'vue';

  const cart = useProductStore();

  defineProps(
    {
      product: {
        type: Object,
      }
    }
  )

  // const emit = defineEmits(
  //   ['remove']
  // );
</script>

<template>
  <div class="cart-item flex items-center gap-6 p-4 bg-gray-100 rounded-lg shadow">
    <img :src="product.image" alt="" class="w-24 h-24 object-cover rounded-lg border">
    <div class="flex-1">
      <h4 class="text-lg font-semibold text-gray-700">{{ product.name }}</h4>
      <p class="text-gray-500">Price: <span class="font-bold text-gray-800">${{ product.price }}</span></p>
      <div class="flex items-center gap-2 mt-2">
        <button class="px-2 py-1 bg-gray-300 rounded hover:bg-gray-400"
          @click="product.quantity > 1 && cart.decreaseQuantity(product.id)"
          :disabled="product.quantity <= 1">-</button>
        <span class="px-3 py-1 bg-white border rounded text-gray-700">{{ product.quantity }}</span>
        <button class="px-2 py-1 bg-gray-300 rounded hover:bg-gray-400"
          @click="cart.increaseQuantity(product.id)">+</button>
      </div>
    </div>
    <button @click="cart.removeCart(product.id)" class="bg-red-900 p-1.5 text-white rounded-md">
      Remove</button>
  </div>
</template>

<script>
  export default {
    name: "CartItem"
  }
</script>
