// src/components/ProductCard.vue
<script setup>
  import { useAuthStore } from '@/stores/auth';
  import { useProductStore } from '@/stores/product';
  import { defineProps } from 'vue';
  import { RouterLink } from 'vue-router';
  defineProps({
    product: {
      type: Object,
      required: true
    }
  });
  const auth = useAuthStore();
  const productState = useProductStore();
</script>

<template>
  <div
    class="product-card bg-white dark:bg-grey rounded-lg shadow-md p-4 relative flex flex-col items-center transition hover:shadow-lg">
    <img :src="product.image" alt=""
      class="w-full h-40 object-cover rounded-md mb-3 transition-transform hover:scale-105">
    <img v-if="product.cart === 1"
      class="cart-button active absolute top-4 right-4 bg-green-100 rounded-full p-2 shadow" src="@/assets/cart.svg"
      height="30px" width="30px" alt="">
    <div class="product-details w-full grid grid-cols-4 gap-2 items-center">
      <div class="product-text col-span-3">
        <h4 class="text-lg font-semibold text-gray-800 truncate">{{ product.name }}</h4>
        <h5 class="text-sm text-gray-500 mt-1">{{ "$ " + product.quantity }}</h5>
      </div>
      <RouterLink to="" v-if="auth.loggedIn" @click.prevent="productState.addToCart(product.id)"
        class="flex justify-end">
        <img class="add-cart cursor-pointer bg-green-50 hover:bg-green-200 rounded-full p-2 transition"
          src="@/assets/cart.svg" height="30px" width="30px" alt="">
      </RouterLink>
    </div>
  </div>
</template>

<style lang="css" scoped>
  .product-card {
    display: grid;
    position: relative;
    grid: none;
    max-width: 14rem;
    width: max-content;
    border: solid 0.00001rem var(--color-border);
    padding: 8px;
    border-radius: 1.5%;

  }

  .product-card>img:hover {
    box-shadow: 1px 2px;

  }

  img {
    max-width: 100%;

  }

  .product-details {
    text-indent: 10px;
    text-indent: 10px;
    display: grid;
  }

  .cart-button {
    position: absolute;
    top: 1rem;
    right: 1rem;
    background-color: rgba(0, 255, 149, 0.24);
    border-radius: 50%;
  }

  .add-cart {
    position: relative;
    right: 6px;
  }

  .add-cart::after {
    content: "+";
  }

  @media (width >=1650px) {
    .product-card {
      max-width: 18rem;
    }
  }

  @media (width >=1450px) {
    .product-card {
      max-width: 16rem;
    }
  }

  @media (width >=1250px) {
    .product-card {
      max-width: 15rem;
    }
  }

  @media (width >=1024px) {
    .product-card {
      max-width: 14rem;
    }
  }
</style>

// qwik-app/src/components/ProductCard.tsx
import { $, component$, useContext } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import { ProductStoreContext } from "~/context/product-store";
import cartImg from "~/media/cart.svg";
// import { Product } from "~/types/products";
type componentProps = {
  name: string;
  image: string;
  price: number;
  cart?: boolean;
  auth: boolean;
  keyid: number;
  // startquantity: number;
};
export default component$<componentProps>(({ keyid, name, image, price, cart, auth }) => {
  const productStore = useContext(ProductStoreContext);

  const onclick = $(() => {
    const product = productStore.products.find((el) => el.id === keyid);
    const cart = productStore.cart.find((el) => el.id === keyid);
    if (product) {
      product.cart = !product.cart;
      if (cart) {
        productStore.cart = productStore.cart.filter((el) => el.id !== keyid);
      } else {
        const cartProduct = product;
        // cartProduct.max = cartProduct.quantity;
        cartProduct.startquantity = 1;
        productStore.cart.push(cartProduct);
      }
    }
    console.log(productStore);
  });
  return (
    <>
      <div class="dark:bg-grey relative flex flex-col items-center rounded-lg bg-white p-2 shadow-md transition hover:shadow-lg">
        <img
          alt=""
          class="mb-3 h-40 w-full rounded-md object-cover transition-transform hover:scale-105"
          height="30"
          width="30"
          src={image}
        />
        {auth && cart ? (
          <img
            class="absolute top-4 right-4 rounded-full bg-green-100 p-2 shadow"
            src={cartImg}
            height="30"
            width="30"
            alt=""
          />
        ) : (
          ""
        )}
        <div class="grid w-full grid-cols-4 items-center gap-2">
          <div class="col-span-3">
            <h4 class="truncate text-lg font-semibold text-gray-800">{name}</h4>
            <h5 class="mt-1 text-sm text-gray-500">{`$ ${price}`}</h5>
          </div>
          {auth ? (
            <Link onClick$={onclick}>
              <img
                class="cursor-pointer rounded-full bg-green-50 p-2 transition hover:bg-green-200"
                src={cartImg}
                height="30"
                width="30"
                alt=""
              />
            </Link>
          ) : (
            ""
          )}
        </div>
      </div>
    </>
  );
});
