// src/views/RegisterContent.vue
<template>
  <div class="grid text-center py-5">
    <img class="py-5" src="https://images.pexels.com/photos/4064840/pexels-photo-4064840.jpeg" alt="">
    <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim consequatur modi corporis sint. Mollitia alias,
      perferendis quas ipsa rem ab a dicta assumenda nostrum distinctio! Asperiores, fuga. Nemo, nobis id!</h1>
  </div>
</template>

<script>
  export default {
    name: "RegisterContent"
  }
</script>

// qwik-app/src/routes/register/RegisterContent.tsx
import { component$ } from "@builder.io/qwik";

export default component$(() => {
  return (
    <div class="grid place-items-center items-center text-center gap-2">
      <img
        src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f"
        width="600"
        height="500"
        alt="Login"
      />
      <h1>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse voluptatibus itaque vel
        deserunt necessitatibus aliquid consequatur quae facilis. Rem neque velit eum nulla corrupti
        earum quas labore exercitationem blanditiis tempore.
      </h1>
    </div>
  );
});
