// qwik-app/src/routes/login/LoginContent.tsx
import { component$ } from "@builder.io/qwik";

export default component$(() => {
  return (
    <div class="grid place-items-center items-center text-center gap-2">
      <h1>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reiciendis sit eveniet quisquam
        tenetur fugiat nostrum dolor consectetur ducimus possimus, obcaecati ipsum omnis, quasi
        ullam nesciunt nemo molestiae laboriosam quos neque!
      </h1>
      <img
        src="https://images.unsplash.com/photo-1506765515384-028b60a970df"
        width="600"
        height="500"
        alt="Login"
      />
    </div>
  );
});

// src/views/LoginContent.vue
<template>
  <div class="self-center object-center place-content-center grid text-center justify-items-center py-5 gap-5 ">
    <h1>Crud Task</h1>
    <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet aperiam dolorum corporis. Vitae voluptatum
      ducimus accusantium quia veritatis rerum iste mollitia. Magni corporis ipsa rem recusandae, totam facilis modi
      ipsum?</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro sed eveniet earum et cumque? Maxime debitis
      illum odio, facere dignissimos nulla enim quo voluptatibus porro, eos rem, ullam ducimus magni.</p>
    <img class="m-auto" src="https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg" alt="">
  </div>
</template>

<script>
  export default {
    name: "LoginContent"
  };
</script>
