// qwik-app/src/routes/register/RegisterForm.tsx
import { $, component$ } from "@builder.io/qwik";
import { useNavigate } from "@builder.io/qwik-city";
import FormButton from "~/components/FormButton";
import InputElement from "~/components/InputElement";

export default component$(() => {
  const nav = useNavigate();

  const handleRegister = $(async (ev: SubmitEvent) => {
    ev.preventDefault();
    const formData = new FormData(ev.target as HTMLFormElement);
    const name = formData.get("name");
    const email = formData.get("email");
    const password = formData.get("password");
    const password_confirmation = formData.get("password_confirmation");

    const res = await fetch("http://127.0.0.1:8000/api/register", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, email, password, password_confirmation }),
    });

    if (res.status === 201) {
      nav("/login");
    }
  });
  return (
    <form onSubmit$={handleRegister} class="grid justify-center gap-1" preventdefault:submit>
      <h1>Regiser</h1>
      <InputElement name="name" text="Name" type="text" />
      <InputElement name="email" text="Email" type="email" />
      <InputElement name="password" text="Password" type="password" />
      <InputElement name="password_confirmation" text="Confirm Password" type="password" />
      <FormButton text="Register" />
    </form>
  );
});

// src/views/RegisterForm.vue
<script setup>

  import InputText from '@/components/InputText.vue';
  import { reactive, ref } from 'vue';
  import { useRouter } from 'vue-router';
  const router = useRouter();

  const form = reactive({
    name: "",
    email: "",
    password: "",
    password_confirmation: "",
  })

  const loading = ref(false);
  const error = ref(false);
  const success = ref(false);

  async function handleRegister() {
    loading.value = ref(true);
    try {
      const response = await fetch("/api/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      console.log(response);
      if (response.status == 201) {
        success.value = ref(true);
        setTimeout(() => {
          router.push({ name: "login" });
        }, 2000);
      }
    } catch (error) {
      error.value = true;
    }
  }
</script>
<template>
  <form @submit.prevent="handleRegister" autocomplete="off">
    <h1>Register</h1>
    <InputText name="name" label="Name" placeholder="Name" type="text" v-model="form.name" />
    <InputText name="email" label="Email" placeholder="Email" type="text" v-model="form.email" />
    <InputText name="password" label="Password" placeholder="Password" type="password" v-model="form.password" />
    <InputText name="password_confirmation" label="Confirm Password" placeholder="Comfirm Password" type="password"
      v-model="form.password_confirmation" />

    <!-- <div class="form-content">
      <label for="email">Name</label>
      <input class="border-1 rounded-md text-base px-1.5" type="text" v-model="form.name" name="name" id="name"
        placeholder="Name" />
    </div>
    <div class="form-content">
      <label for="email">Email</label>
      <input class="border-1 rounded-md text-base px-1.5" type="text" v-model="form.email" name="email" id="email"
        placeholder="Email" />
    </div>
    <div class="form-content">
      <label for="password">Password</label>
      <input class="border-1 rounded-md text-base px-1.5" type="password" v-model="form.password" name="password"
        id="password" placeholder="Password" />
    </div>
    <div class="form-content">
      <label for="password">Confirm Password</label>
      <input class="border-1 rounded-md text-base px-1.5" type="password" v-model="form.password_confirmation"
        name="password_confirmation" id="password_confirmation" placeholder="Confirm Password" />
    </div> -->
    <div class="form-content">
      <button class="border-1 p-1" name="submit" id="submit" :disabled="loading">{{ loading ? "Registering" :
        "Register" }}</button>
    </div>
    <div class="text-red" v-if="error">Something went wrong</div>
    <div class="text-success" v-if="success">Account created successfully</div>
  </form>
</template>

<script>
  export default {
    name: "RegisterForm",
  }
</script>
